name: polymind
services:
  polymind:
    image: ghcr.io/toeverything/polymind:${POLYMIND_REVISION:-stable}
    container_name: polymind_server
    ports:
      - '${PORT:-3010}:3010'
    depends_on:
      postgres:
        condition: service_healthy
      polymind_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.polymind/storage
      - ${CONFIG_LOCATION}:/root/.polymind/config
    env_file:
      - .env
    environment:
      - LOCAL_MODE=true
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-polymind}
      - POLYMIND_INDEXER_ENABLED=false
    restart: unless-stopped

  polymind_migration:
    image: ghcr.io/toeverything/polymind:${POLYMIND_REVISION:-stable}
    container_name: polymind_migration_job
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.polymind/storage
      - ${CONFIG_LOCATION}:/root/.polymind/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - .env
    environment:
      - LOCAL_MODE=true
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-polymind}
      - POLYMIND_INDEXER_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: pgvector/pgvector:pg16
    container_name: polymind_postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-polymind}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${DB_USERNAME}", '-d', "${DB_DATABASE:-polymind}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
